openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    Post:
      type: object
      required:
        - id
        - title
        - category
        - company
        - feeds
        - caption
        - type
        - location
        - contact
        - startsAt
        - endsAt
        - link
        - tags
      properties:
        id:
          type: string
        title:
          type: string
        category:
          type: string
        company:
          type: string
        feeds:
          type: array
          items:
            type: string
        caption:
          type: string
        type:
          type: string
        location:
          type: string
        contact:
          type: string
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        link:
          type: string
        tags:
          type: array
          items:
            type: string
