openapi: 3.0.0
info:
  title: Aroundy
  description: Aroundy 앱 및 어드민 페이지 공용 API
  version: v1.0.0
tags:
  - name: App
paths:
  /posts:
    head:
      tags:
        - App
      operationId: Posts_preflightPosts
      summary: Post 갯수 조회
      description: |-
        주어진 필터로 검색된 Post 갯수를 보고한다.

        실시간 검색 결과 버튼에서 사용한다.
      parameters:
        - $ref: '#/components/parameters/Posts.QueryOption.category'
        - $ref: '#/components/parameters/Posts.QueryOption.sort'
        - $ref: '#/components/parameters/Posts.QueryOption.companies'
        - $ref: '#/components/parameters/Posts.QueryOption.priceMin'
        - $ref: '#/components/parameters/Posts.QueryOption.priceMax'
        - $ref: '#/components/parameters/Posts.QueryOption.location'
        - $ref: '#/components/parameters/Posts.QueryOption.ended'
      responses:
        '204':
          description: 항목 수 헤더 래퍼
          headers:
            X-Total-Records:
              required: true
              description: 검색된 총 항목 수
              schema:
                type: integer
                format: uint64
    get:
      tags:
        - App
      operationId: Posts_fetchPosts
      summary: Post 조회 및 검색
      description: Post 목록을 추천 기준에 따라 조회 및 검색한다.
      parameters:
        - $ref: '#/components/parameters/Posts.QueryOption.category'
        - $ref: '#/components/parameters/Posts.QueryOption.sort'
        - $ref: '#/components/parameters/Posts.QueryOption.companies'
        - $ref: '#/components/parameters/Posts.QueryOption.priceMin'
        - $ref: '#/components/parameters/Posts.QueryOption.priceMax'
        - $ref: '#/components/parameters/Posts.QueryOption.location'
        - $ref: '#/components/parameters/Posts.QueryOption.ended'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            X-Total-Records:
              required: true
              description: 검색된 총 항목 수
              schema:
                type: integer
                format: uint64
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                  - page
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                    description: 실제 데이터
                  page:
                    type: object
                    properties:
                      totalRecords:
                        type: integer
                        format: uint64
                        description: 검색된 총 항목 수
                      totalPages:
                        type: integer
                        format: uint64
                        description: 총 페이지 갯수
                      pageSize:
                        type: integer
                        format: uint64
                        description: 현재 페이지에 포함된 항목 수
                      nextPage:
                        type: integer
                        format: uint64
                        nullable: true
                        description: |-
                          다음 페이지 번호

                          현재 페이지가 마지막 페이지인 경우 `nextPage`는 `null`이 된다.
                      nextRecords:
                        type: integer
                        format: uint64
                        description: |-
                          다음 페이지에 나타날 항목 수

                          다음 페이지가 마지막 페이지일 경우 페이지 크기로 나누어 떨어지지 않는 값이 들어간다.
                          다음 페이지 로딩 전 표시할 스켈레톤 갯수를 맞추기 위해 사용한다.
                    required:
                      - totalRecords
                      - totalPages
                      - pageSize
                      - nextPage
                      - nextRecords
                    description: 페이지 메타데이터
                description: 항목 수 헤더 래퍼
    post:
      operationId: Posts_createPost
      summary: 새 Post 등록
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePost'
  /posts/{id}:
    patch:
      operationId: Posts_updatePost
      summary: Post 수정
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                category:
                  type: string
                  description: 카테고리
                feeds:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 10
                  description: 피드 배너 이미지 목록
                caption:
                  type: string
                  maxLength: 2200
                  description: Post 상세 내용
                type:
                  allOf:
                    - $ref: '#/components/schemas/EventType'
                  description: 이벤트 유형
                location:
                  type: string
                  nullable: true
                  description: 상세주소
                contact:
                  type: string
                  nullable: true
                  description: 연락처
                startsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 오픈일
                endsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 종료일
                link:
                  type: string
                  format: uri
                  nullable: true
                  description: 출처 링크
                tags:
                  type: array
                  items:
                    type: string
                  description: 태그 목록
              description: The template for adding optional properties.
    delete:
      operationId: Posts_deletePost
      summary: Post 삭제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /posts/{id}/like:
    patch:
      tags:
        - App
      operationId: Posts_like
      summary: 좋아요 추가
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /posts/{id}/save:
    patch:
      tags:
        - App
      operationId: Posts_save
      summary: 마이페이지에 저장
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /posts/{id}/unlike:
    patch:
      tags:
        - App
      operationId: Posts_unlike
      summary: 좋아요 해제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /posts/{id}/unsave:
    patch:
      tags:
        - App
      operationId: Posts_unsave
      summary: 마이페이지에서 저장 취소
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /posts/{id}/view:
    patch:
      tags:
        - App
      operationId: Posts_view
      summary: 조회수 증가
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
components:
  parameters:
    Posts.QueryOption.category:
      name: category
      in: query
      required: false
      description: 한정할 카테고리
      schema:
        type: string
    Posts.QueryOption.companies:
      name: companies
      in: query
      required: false
      description: 브랜드 한정 필터
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false
    Posts.QueryOption.ended:
      name: ended
      in: query
      required: false
      description: |-
        이벤트 상태 필터

        - `undefined`: 상태 무관
        - `true`: 종료된 이벤트만
        - `false`: 진행 중인 이벤트만
      schema:
        type: boolean
    Posts.QueryOption.location:
      name: location
      in: query
      required: false
      description: |-
        지역 필터

        - 전체
        - 서울
        - 경기
        - 인천
        - 강원
        - 세종
        - 대전
        - 충북
        - 충남
        - 부산
        - 대구
        - 울산
        - 경북
        - 경남
        - 광주
        - 전북
        - 전남
        - 제주
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false
    Posts.QueryOption.priceMax:
      name: priceMax
      in: query
      required: false
      description: |-
        최대 가격 필터

        단위는 10k KRW
      schema:
        type: integer
        format: uint64
    Posts.QueryOption.priceMin:
      name: priceMin
      in: query
      required: false
      description: |-
        최소 가격 필터

        단위는 10k KRW
      schema:
        type: integer
        format: uint64
    Posts.QueryOption.sort:
      name: sort
      in: query
      required: false
      description: 추천 기준
      schema:
        $ref: '#/components/schemas/Posts.SortOption'
  schemas:
    BasePost:
      type: object
      required:
        - title
        - category
        - feeds
        - caption
        - type
        - location
        - contact
        - startsAt
        - endsAt
        - link
        - tags
      properties:
        title:
          type: string
          description: 제목
        category:
          type: string
          description: 카테고리
        feeds:
          type: array
          items:
            type: string
            format: uri
          maxItems: 10
          description: 피드 배너 이미지 목록
        caption:
          type: string
          maxLength: 2200
          description: Post 상세 내용
        type:
          allOf:
            - $ref: '#/components/schemas/EventType'
          description: 이벤트 유형
        location:
          type: string
          nullable: true
          description: 상세주소
        contact:
          type: string
          nullable: true
          description: 연락처
        startsAt:
          type: string
          format: date-time
          nullable: true
          description: 오픈일
        endsAt:
          type: string
          format: date-time
          nullable: true
          description: 종료일
        link:
          type: string
          format: uri
          nullable: true
          description: 출처 링크
        tags:
          type: array
          items:
            type: string
          description: 태그 목록
      description: 상속용 Post 클래스
    Company:
      type: object
      required:
        - id
        - name
        - logo
        - status
      properties:
        id:
          type: string
          format: uuid
          description: 기업 고유 ID
        name:
          type: string
          description: 기업명
        logo:
          type: string
          format: uri
          description: 기업 로고
        status:
          type: string
          description: 상태
      description: 기업 정보
    CreatePost:
      type: object
      required:
        - companyId
      properties:
        companyId:
          type: string
          format: uuid
          description: Post를 생성할 기업의 ID
      allOf:
        - $ref: '#/components/schemas/BasePost'
      description: Post 생성 시 입력할 정보
    EventType:
      type: string
      enum:
        - online
        - offline
        - both
      description: |-
        이벤트 유형

        - `online`: 온라인
        - `offline`: 오프라인
        - `both`: 온/오프라인
    Post:
      type: object
      required:
        - id
        - company
        - likes
        - views
        - isLiked
        - isSaved
      properties:
        id:
          type: string
          format: uuid
          description: Post의 고유 ID
        company:
          allOf:
            - $ref: '#/components/schemas/Company'
          description: Post를 등록한 기업
        likes:
          type: integer
          format: uint64
          description: 좋아요 수
        views:
          type: integer
          format: uint64
          description: 조회수
        isLiked:
          type: boolean
          description: 현재 로그인된 사용자가 이미 좋아요한 Post인지 여부
        isSaved:
          type: boolean
          description: 현재 로그인된 사용자가 이미 마이페이지에 저장한 Post인지 여부
      allOf:
        - $ref: '#/components/schemas/BasePost'
      description: Post 정보
    Posts.SortOption:
      type: string
      enum:
        - recommended
        - latest
        - deadline
        - higherDiscount
        - lowserDiscount
        - higherPrice
        - lowserPrice
        - farthest
        - nearest
      description: |-
        Post 추천 기준

        - `recommended`: 추천순
        - `latest`: 게시순
        - `deadline`: 마감순
        - `higherDiscount`: 높은 할인순
        - `lowserDiscount`: 낮은 할인순
        - `higherPrice`: 높은 가격순
        - `lowserPrice`: 낮은 가격순
        - `farthest`: 먼 거리순
        - `nearest`: 가까운 거리순
    Versions:
      type: string
      enum:
        - v0.1.0
        - v1.0.0
servers:
  - url: https://api.aroundy.teambigbox.com
    description: 엔드포인트
    variables: {}
