openapi: 3.0.0
info:
  title: Aroundy
  description: Aroundy 앱 및 어드민 페이지 공용 API
  version: v1.0.0
tags: []
paths:
  /posts:
    get:
      operationId: Posts_fetchPosts
      summary: Post 조회 및 검색
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: Posts_createPost
      summary: 새 Post 등록
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePost'
  /posts/{id}:
    patch:
      operationId: Posts_updatePost
      summary: Post 수정
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                category:
                  type: string
                  description: 카테고리
                feeds:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 10
                  description: 피드 배너 이미지 목록
                caption:
                  type: string
                  maxLength: 2200
                  description: Post 상세 내용
                type:
                  allOf:
                    - $ref: '#/components/schemas/EventType'
                  description: 이벤트 유형
                location:
                  type: string
                  nullable: true
                  description: 상세주소
                contact:
                  type: string
                  nullable: true
                  description: 연락처
                startsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 오픈일
                endsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 종료일
                link:
                  type: string
                  format: uri
                  nullable: true
                  description: 출처 링크
                tags:
                  type: array
                  items:
                    type: string
                  description: 태그 목록
              description: The template for adding optional properties.
    delete:
      operationId: Posts_deletePost
      summary: Post 삭제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /posts/{id}/like:
    patch:
      operationId: Posts_like
      summary: 좋아요 추가
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                category:
                  type: string
                  description: 카테고리
                feeds:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 10
                  description: 피드 배너 이미지 목록
                caption:
                  type: string
                  maxLength: 2200
                  description: Post 상세 내용
                type:
                  allOf:
                    - $ref: '#/components/schemas/EventType'
                  description: 이벤트 유형
                location:
                  type: string
                  nullable: true
                  description: 상세주소
                contact:
                  type: string
                  nullable: true
                  description: 연락처
                startsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 오픈일
                endsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 종료일
                link:
                  type: string
                  format: uri
                  nullable: true
                  description: 출처 링크
                tags:
                  type: array
                  items:
                    type: string
                  description: 태그 목록
              description: The template for adding optional properties.
  /posts/{id}/unlike:
    patch:
      operationId: Posts_unlike
      summary: 좋아요 해제
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                category:
                  type: string
                  description: 카테고리
                feeds:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 10
                  description: 피드 배너 이미지 목록
                caption:
                  type: string
                  maxLength: 2200
                  description: Post 상세 내용
                type:
                  allOf:
                    - $ref: '#/components/schemas/EventType'
                  description: 이벤트 유형
                location:
                  type: string
                  nullable: true
                  description: 상세주소
                contact:
                  type: string
                  nullable: true
                  description: 연락처
                startsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 오픈일
                endsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 종료일
                link:
                  type: string
                  format: uri
                  nullable: true
                  description: 출처 링크
                tags:
                  type: array
                  items:
                    type: string
                  description: 태그 목록
              description: The template for adding optional properties.
  /posts/{id}/view:
    patch:
      operationId: Posts_view
      summary: 조회수 증가
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                category:
                  type: string
                  description: 카테고리
                feeds:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 10
                  description: 피드 배너 이미지 목록
                caption:
                  type: string
                  maxLength: 2200
                  description: Post 상세 내용
                type:
                  allOf:
                    - $ref: '#/components/schemas/EventType'
                  description: 이벤트 유형
                location:
                  type: string
                  nullable: true
                  description: 상세주소
                contact:
                  type: string
                  nullable: true
                  description: 연락처
                startsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 오픈일
                endsAt:
                  type: string
                  format: date-time
                  nullable: true
                  description: 종료일
                link:
                  type: string
                  format: uri
                  nullable: true
                  description: 출처 링크
                tags:
                  type: array
                  items:
                    type: string
                  description: 태그 목록
              description: The template for adding optional properties.
components:
  schemas:
    BasePost:
      type: object
      required:
        - title
        - category
        - feeds
        - caption
        - type
        - location
        - contact
        - startsAt
        - endsAt
        - link
        - tags
      properties:
        title:
          type: string
          description: 제목
        category:
          type: string
          description: 카테고리
        feeds:
          type: array
          items:
            type: string
            format: uri
          maxItems: 10
          description: 피드 배너 이미지 목록
        caption:
          type: string
          maxLength: 2200
          description: Post 상세 내용
        type:
          allOf:
            - $ref: '#/components/schemas/EventType'
          description: 이벤트 유형
        location:
          type: string
          nullable: true
          description: 상세주소
        contact:
          type: string
          nullable: true
          description: 연락처
        startsAt:
          type: string
          format: date-time
          nullable: true
          description: 오픈일
        endsAt:
          type: string
          format: date-time
          nullable: true
          description: 종료일
        link:
          type: string
          format: uri
          nullable: true
          description: 출처 링크
        tags:
          type: array
          items:
            type: string
          description: 태그 목록
      description: 상속용 Post 클래스
    Company:
      type: object
      required:
        - id
        - name
        - logo
        - status
      properties:
        id:
          type: string
          format: uuid
          description: 기업 고유 ID
        name:
          type: string
          description: 기업명
        logo:
          type: string
          format: uri
          description: 기업 로고
        status:
          type: string
          description: 상태
      description: 기업 정보
    CreatePost:
      type: object
      required:
        - companyId
      properties:
        companyId:
          type: string
          format: uuid
          description: Post를 생성할 기업의 ID
      allOf:
        - $ref: '#/components/schemas/BasePost'
      description: Post 생성 시 입력할 정보
    EventType:
      type: string
      enum:
        - online
        - offline
        - both
      description: 이벤트 유형
    Post:
      type: object
      required:
        - id
        - company
        - likes
        - views
        - isLiked
      properties:
        id:
          type: string
          format: uuid
          description: Post의 고유 ID
        company:
          allOf:
            - $ref: '#/components/schemas/Company'
          description: Post를 등록한 기업
        likes:
          type: integer
          format: uint64
          description: 좋아요 수
        views:
          type: integer
          format: uint64
          description: 조회수
        isLiked:
          type: boolean
          description: 현재 로그인된 사용자가 이미 좋아요한 Post인지 여부
      allOf:
        - $ref: '#/components/schemas/BasePost'
      description: Post 정보
    Versions:
      type: string
      enum:
        - v0.1.0
        - v1.0.0
servers:
  - url: https://api.aroundy.teambigbox.com
    description: 엔드포인트
    variables: {}
